spring.application.name=payment-service
server.port=8083

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5434/payment-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AWS
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

# SQS
booking.events.queue.url=https://sqs.us-east-1.amazonaws.com/781195019885/booking-events-payment